### PR TITLE
Fix abstract classes initialization

### LINKED ISSUE #18: Abstract implementation of Enumeration seems to break StaticConstructorLoader
Please consider the following example (simplified code for readability):

EnumerationWrapper.php
```php
abstract class EnumerationWrapper extends Enumeration{
// added some wrapper logic
}
```
FieldReadMode.php
```php
final class FieldReadMode extends EnumerationWrapper{
    public static $none;
    public static $all;
}
```

If I add the `FieldReadMode::initiailize()` call to the end of the FieldReadMode.php file, everything works as expected, but if I instead use the `StaticConstructorLoader` class in order to simplify the initialization, I end up with an error like:
> PHP Fatal error:  During class fetch: Uncaught Error: Cannot instantiate abstract class `EnumerationWrapper`

I believe this is due to the `__constructStatic()` method within `Enumeration` initializing any child class, including abstract ones.

If I overlooked something and this is user error, please let me know. Otherwise I've come up with a solution below.

---

I was able to circumvent this issue by adding the following method to `Enumeration`:
```php
protected static function shouldInitialize(): bool
{
    return true;
}
```

and changing the `__constructStatic()` method to be:
```php
final public static function __constructStatic(): void
{
    if (self::class === static::class || !static::shouldInitialize())
    {
        return;
    }
    static::initialize();
}
```

and finally overriding the new method in `EnumerationWrapper` to be
```php
protected static function shouldInitialize(): bool
{
    return self::class !== static::class;
}
```
I'm not saying this is the most elegant or valid solution, but it's one that is working for me currently.

If you would prefer I fork the project and make a PR with this implementation let me know. Thanks for your work on this project!

### PR DESCRIPTION
**Pull request by dbalabka**
Fixes #18

### CODE REVIEW

File: tests/Enumeration/Fixtures/AbstractAction.php [hunk 1]
```diff
@@ -0,0 +1,22 @@
+<?php
+declare(strict_types=1);
+
+namespace Dbalabka\Enumeration\Tests\Fixtures;
+
+use Dbalabka\Enumeration\Enumeration;
+use function version_compare;
+use const PHP_VERSION;
+
+if (version_compare(PHP_VERSION, '7.4.0beta', '<')) {
```
Comment (oleg-andreyev) [inline tests/Enumeration/Fixtures/AbstractAction.php]: 7.4 is already released, IMO it's time to remove beta prefix, also I think it's better to use PHP_VERSION_ID (70400)

Comment (dbalabka) [reply tests/Enumeration/Fixtures/AbstractAction.php]: I will do

**Comment by dbalabka** [comment]
Need to improve coverage and this ticket can be merged:
https://coveralls.io/builds/29048979/source?filename=src%2FEnumeration%2FEnumeration.php#L58
